# Generated by Django 5.2.7 on 2026-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_citizenprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
