# Generated by Django 5.2.7 on 2025-11-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
