# Generated by Django 5.2.7 on 2025-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_delete_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
