# Generated by Django 5.2.7 on 2026-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_issuereport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/'),
        ),
    ]
