# Generated by Django 5.2.7 on 2025-11-07 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_emergencyalert_issuecomment_issuevote'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('movie_ticket', 'Movie Ticket'), ('shopping_voucher', 'Shopping Voucher'), ('food_coupon', 'Food Coupon'), ('gift_card', 'Gift Card'), ('cashback', 'Cashback')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='validity_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='fulfillment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('contributor', 'Contributor'), ('champion', 'Champion'), ('hero', 'Hero')], default='beginner', max_length=20),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('issue_reported', 'Issue Reported'), ('issue_resolved', 'Issue Resolved'), ('reward_claimed', 'Reward Claimed'), ('bonus', 'Bonus')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.issuereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
