# Generated by Django 5.2.7 on 2026-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_citizenprofile_joined_at_reward_reward_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('contributor', 'Contributor'), ('champion', 'Champion'), ('hero', 'Hero')], default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('issue_reported', 'Issue Reported'), ('issue_resolved', 'Issue Resolved'), ('reward_claimed', 'Reward Claimed'), ('bonus', 'Bonus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('movie_ticket', 'Movie Ticket'), ('shopping_voucher', 'Shopping Voucher'), ('food_coupon', 'Food Coupon'), ('gift_card', 'Gift Card'), ('cashback', 'Cashback')], max_length=50),
        ),
    ]
