# Generated by Django 5.2.7 on 2026-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_citizenprofile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('movie_ticket', 'Movie Ticket'), ('shopping_voucher', 'Shopping Voucher'), ('food_coupon', 'Food Coupon'), ('gift_card', 'Gift Card'), ('cashback', 'Cashback')], max_length=30),
        ),
    ]
