# Generated by Django 5.2.7 on 2026-03-12 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_citizenprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitizenProfile',
            new_name='CitizenRewardProfile',
        ),
    ]
